### ISSUE TITLE
EUI + HRA Portal: Remove info modal functionality and move content to HRA Portal EUI page

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/ccf-ui#1018]
# EUI + HRA Portal: Remove info modal functionality and move content to HRA Portal EUI page

## To Do
- [x]  Update the [EUI HRA Portal page](https://humanatlas.io/exploration-user-interface) with content from the [EUI static content doc](https://docs.google.com/document/d/1fFBp6MqKxPwD2mjDSnFo0MRuJJbSP4GK09BwKgFO5OU/edit#heading=h.gtnkp5c2gyox). See the [Figma design file](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=411-7251&t=mxvFbtpoTqcy4b57-4) for specifications.
- [ ] Remove the Spatial Search info modal and the About info modal.
- [ ] On click of the About Info button, a new tab opens to the top of the [EUI HRA Portal page](https://humanatlas.io/exploration-user-interface).
- [ ] On click of the Spatial Search button, a new tab opens to the Spatial Search tutorial part of the [EUI HRA Portal page](https://humanatlas.io/exploration-user-interface). This tab must be anchored to the Spatial Search tutorial title, see  [Figma design file](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=4026-21208&t=mxvFbtpoTqcy4b57-4).

## Resources
- [EUI on HRA Portal](https://humanatlas.io/exploration-user-interface)
- [HRA Portal GitHub repo](https://github.com/cns-iu/humanatlas.io)
- [Google Doc: EUI static content](https://docs.google.com/document/d/1fFBp6MqKxPwD2mjDSnFo0MRuJJbSP4GK09BwKgFO5OU/edit#heading=h.gtnkp5c2gyox)
- [Figma design file: HRA Portal EUI Page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=411-7251&t=mxvFbtpoTqcy4b57-4)

### About Info button
![image](https://user-images.githubusercontent.com/97060856/228295282-0b43202d-65c2-435d-8b47-ee7df1ac89bb.png)

### About Info modal
![image](https://user-images.githubusercontent.com/97060856/228295460-0dbdaa1d-1633-4c37-a1e2-a139f13944ed.png)

### Spatial Search Info button
![image](https://user-images.githubusercontent.com/97060856/228295110-7ba57c17-0f9d-4522-9091-627baf6ed2d4.png)

### Spatial Search Info modal
![image](https://user-images.githubusercontent.com/97060856/228294957-3476fdd2-351f-4b1a-9425-9e97a8069a7c.png)

**Comment by bherr2** [comment]
Hold off on this until we get consensus (probably going to close)

**Comment by libby-maier** [comment]
This is not needed. Closing.
