### ISSUE TITLE
RUI - Ability to pass the organ ID instead of the whole object (High priority)

### ISSUE THREAD

**Issue by RFSH** [hubmapconsortium/ccf-ui#1080]
The created registry file encodes the organ information under `placement.target` as a string. But we cannot use the same ID as an input to the app and have to create an object instead. To solve this, we have to hardcode a mapping from IDs to the object that CCF-RUI accepts. Something like the following:

  ```ts
  const ORGAN_LOOKUP = {
    'http://purl.org/ccf/latest/ccf.owl#VHFRightKidney': {
      'name': 'kidney',
      'side': 'right',
      'sex': 'female'
    },
    'http://purl.org/ccf/latest/ccf.owl#VHMRightKidney': {
      'name': 'kidney',
      'side': 'right',
      'sex': 'male'
    },
    'http://purl.org/ccf/latest/ccf.owl#VHFLeftKidney': {
      'name': 'kidney',
      'side': 'left',
      'sex': 'female'
    },
    'http://purl.org/ccf/latest/ccf.owl#VHMLeftKidney': {
      'name': 'kidney',
      'side': 'left',
      'sex': 'male'
    }
  };

  // `data` is the stored json that we're feeding into the app.

  // preselect the organ
  if (data && data.placement && data.placement.target) {
    const org = ORGAN_LOOKUP[data.placement.target];
    if (org) {
      rui.organ = org;
    }
  }
  ```

It would be much better if we could simply pass the organ ID to the app.

P.S. I edited this description so this is only about the issue that we would like to be solved (originally it was the "second point" that the next comment is referring to).

<details>
 <summary>Click here to see the description for the "first point" that the comment is referring to.</summary>

If we provide both the user and organ to CCF-RUI, it will start the app without asking for this information from the user. I would assume it should also be able to handle just providing a user or organ. But that's not the case.
  - If we only provide the organ, it will correctly highlight the selected organ. But after choosing the first and last names, the "Start Registration" button stays disabled. The button becomes enabled only after clicking on an organ (defeating the purpose of preselecting an organ).
  - If we only provide the user, it will correctly populate the first and last names. But after selecting an organ, the "Start Registration" button stays disabled. The button becomes enabled only if you change the "first name" or "last name" inputs (you basically have to trigger the `onchange` event for first name or last name input).

While this looks like a buggy behavior that you might want to fix, we're not going to use the app in this mode.
</details>

**Comment by edlu77** [comment]
The issues have been addressed in the latest staging build on develop.

Now there are three ways to pass in the organ info:
- An object `{name: "Kidney", side: "left", sex: "female"}`
- A stringified object `'{"name": "Kidney", "side": "left", "sex": "female"}'`
- Organ id `'http://purl.org/ccf/latest/ccf.owl#VHFLeftKidney'`

In addition, the Start Registration button will now exhibit the proper highlighting behavior.
