### ISSUE TITLE
RUI - Race condition issue while loading existing registry

### ISSUE THREAD

**Issue by RFSH** [hubmapconsortium/ccf-ui#1089]
The RUI tool has a race condition when it's trying to initialize the app with an existing registry. Because of this, the app fails to show the selected organ image on page load, and the extra metadata (Anatomical structures, Anatomical structure tags, Landmarks) are not populated on the page either.

You can consistently reproduce this by intentionally turning off the browser cache and throttling your network. The following is how I did it in Firefox:
1. Go to https://hubmapconsortium.github.io/ccf-ui/rui/
2. Open the browser console and add the `TEST_EMBEDDED` local storage to turn on testing the existing registry feature.
3. Go to the network tab and make sure "Disable cache" is selected. Also, choose "Good 3G" in the throttling dropdown.
4. Refresh the page.

What I expect to see:
![expected-page](https://github.com/hubmapconsortium/ccf-ui/assets/2129750/06fbf12d-f6cd-43e8-9dee-47c4ad69aa23)

What I see instead:
![broken-page](https://github.com/hubmapconsortium/ccf-ui/assets/2129750/4e8d6adc-7c7b-4730-a286-a7921abee0d6)

**Comment by bherr2** [comment]
Also from @RFSH :

One thing that I didn’t mention in the issue and is actually worse and can cause issues is that if you download the registry in this scenario, other than missing ccf_annotations , the placement.target  is also missing. and given that we’re trying to validate the organ and allow only a certain organs, users cannot submit the registry when this race condition happens.
In our scenario, we have to first fetch the existing file from our servers and then we can populate user, organ, and editRegistration. When I was testing this I realized if there’s a large delay between DOMContentLoaded and populating these values, the app will almost always show the initial form to users. you can test it here: https://dev.gudmap.org/~ashafaei/apps/hra/rui_async.html
To fix this, I’m waiting until we get the file and then I’m injecting the ccf-rui  element with javascript. something like this: https://dev.gudmap.org/~ashafaei/apps/hra/rui_async_inject.html
The added delay for editRegistration helps a bit but I still see the race condition most of the times:
https://dev.gudmap.org/~ashafaei/apps/hra/rui_test_delay.html
https://dev.gudmap.org/~ashafaei/apps/hra/rui_async_delay.html
https://dev.gudmap.org/~ashafaei/apps/hra/rui_async_inject_delay.html

**Comment by RFSH** [comment]
After updating my CCF-UI to be based on the latest staging build, I cannot reproduce this issue anymore. Thank you!
