### ISSUE TITLE
Filters Flyout Improvements

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/ccf-ui#1107]
Design work needed for responsive menu listening in the EUI's filter menu

- [x] Update verbiage for GTEx
- [x] Responsive design mockups for filter menu on smaller breakpoints

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/135a1f68-7b84-40f8-82ee-ea3d6acbb7e1)

**Comment by libby-maier** [comment]
Hi, @edlu77 & @axdanbol!

What is the current font size being used in the checkbox pattern in the Filters Flyout? This information will help me design an improvement for this component. Thank you & Happy Friday!

P.S. - Here are some Midjourney vibes for you two on this sunny Friday!

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/b445a2c6-b8f3-44b8-aa47-c2835b58f4b5)
![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/9675d104-f635-436a-8773-9ae30ea4f447)

**Comment by edlu77** [comment]
The font in the filters flyout is 16px.

Thanks for sharing, have a good Friday as well! 😊

> Hi, @edlu77 & @axdanbol!
> 
> What is the current font size being used in the checkbox pattern in the Filters Flyout? This information will help me design an improvement for this component. Thank you & Happy Friday!
> 
> P.S. - Here are some Midjourney vibes for you two on this sunny Friday!
> 
> ![image](https://user-images.githubusercontent.com/97060856/273296511-b445a2c6-b8f3-44b8-aa47-c2835b58f4b5.png) ![image](https://user-images.githubusercontent.com/97060856/273296625-9675d104-f635-436a-8773-9ae30ea4f447.png)

**Comment by libby-maier** [comment]
# Filters Flyout Improvements

I updated the title to reflect the desired change. It wasn't necessarily a responsive issue. I've updated the spacing/padding/proportions of the Filters Flyout in Figma. Reach out with questions if you have them. Thanks so much!

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/2ae848db-c5c0-4b98-9187-5e189efe6aba)

## To Do
- [ ] Increase the width of the component.
- [ ] Organize the rows as specified.
- [ ] Adjust the gaps/padding as specified.
- [ ] Apply Filters should read in Title Case instead of upper case.

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/ee5e06db-bbac-4574-ae04-f40595c858d4)


![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/90cf6bbd-25b7-4b22-a49d-85c0ba8ebd65)

## Resources
- [Figma Design File: New Filters Flyout Component (Oct 2023)](https://www.figma.com/file/AxRgTJl5PUE7tNqk0VsMc3/EUI?type=design&node-id=2494-32854&mode=design&t=M4aIH1cmdF33BMOK-4)
- [Figma Design File: Old Filters Flyout information](https://www.figma.com/file/AxRgTJl5PUE7tNqk0VsMc3/EUI?type=design&node-id=2499-33467&mode=design&t=M4aIH1cmdF33BMOK-4)
- [Figma Design File: New Filters Flyout information](https://www.figma.com/file/AxRgTJl5PUE7tNqk0VsMc3/EUI?type=design&node-id=2499-33471&mode=design&t=M4aIH1cmdF33BMOK-4)
