### ISSUE TITLE
Incorrect formatting of ccf-rui details label

### ISSUE THREAD

**Issue by tjmadonna** [hubmapconsortium/ccf-ui#1112]
When organ side isn't specified in `ccf-details-label`, the extra comma is still added to the detail label

<img width="874" alt="Screenshot 2023-09-20 at 12 39 48 PM" src="https://github.com/hubmapconsortium/ccf-ui/assets/8182608/95493bca-98fa-4b42-a20a-da1bf4919e55">

**Comment by bherr2** [comment]
Thanks for filing, I'll put it on our list for bug fixes coming up!
