### ISSUE TITLE
RUI Header updates

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/ccf-ui#1113]
# RUI Header updates

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/7dc30a94-f196-4e2f-b430-c0ac5d54f184)

The RUI header has two small updates:
- [x] Change the title from CCF Registration to HRA Registration
- [x] Update the HRA Registration font color to #C2CAE5

## Resources
- Inspect the Figma design file: [Header component](https://www.figma.com/file/KMti4IJGUUQrle2rl1n2Go/RUI?type=design&node-id=664-433&mode=dev)

**Comment by jsaikiran19** [comment]
Done.
