### ISSUE TITLE
Add global axes to denote X, Y, Z directions for the organ

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1114]
Example (prototyped in Unity):

![250567046-daf1a4b9-46d9-44e0-a9d2-1b321962c385](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/fe932fd9-27e9-479a-93ce-7d3c27915099)

**Comment by libby-maier** [comment]
# Add global axes to denote X, Y, Z directions for the organ

Add the same axes used in the EUI Spatial Search to the scene in the RUI.

## Resources
- [RUI 3D Interactions Unity Prototype](https://cns-iu.github.io/rui-3d-interactions/)
- [Exploration User Interface (EUI)](https://portal.hubmapconsortium.org/ccf-eui)

## EUI Spatial Search Axes
![592B6BF1-E4B0-45E2-8E3A-3CBB8D6289E7](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/f1c2ccee-3700-49bb-bbb0-439e6af8f662)
