### ISSUE TITLE
RUI - Reset to the starting registration

### ISSUE THREAD

**Issue by RFSH** [hubmapconsortium/ccf-ui#1118]
As I mentioned [here](https://github.com/hubmapconsortium/ccf-ui/issues/1090#issuecomment-1726670048), changing the organ is currently resetting the coordinates, and as a result, all the annotations and metadata are getting lost. 

It would be great if RUI had a reset button. So if a user accidentally changes the organ or makes any other modifications, they can return to the registration file with which they started the app.

**Comment by bherr2** [comment]
Ok, we'll look into it.This method might actually be harder than what you proposed originally.

**Comment by edlu77** [comment]
This has been fixed in the latest staging build of develop. Now clicking the reset button in the staging area returns everything to the initial registration state.

https://github.com/hubmapconsortium/ccf-ui/assets/36934022/e3ce69d6-280d-4451-abb4-36dc5534d75a
