### ISSUE TITLE
Add 'carbon rods' to tissue blocks

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1120]

**Comment by libby-maier** [comment]
# Add 'carbon rods' to tissue blocks

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/45aa5a35-ee1c-4345-bae3-c3c3b1a08851)
![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/3c29d6fc-dae5-4b3b-8b37-0d4830ed04e8)

## UX Notes
- This was prototyped in Unity so please reach out to @andreasbueckle or myself if you have questions!
