### ISSUE TITLE
Add reference_organ and sex field to response for CCF API /scene

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1128]
https://ccf-api.hubmapconsortium.org/#/operations/scene returns an array of nodes (organs and all tissue blocks). For organs, we should include the ```sex``` in the response, and for tissue blocks, we should include ```reference_organ``` so they can be matched to the organs in the response.

**Comment by bherr2** [comment]
I was able to add sex to reference organs in the scene, but adding reference_organ to tissue blocks may be a bit harder and I may have to come back to.

**Comment by bherr2** [comment]
Currently just on staging: https://r5i95k35v5.us-east-2.awsapprunner.com/#/operations/scene

**Comment by bherr2** [comment]
For tissue blocks, to check their reference organ, check against their ccf_annotations. Workaround is detailed [here](https://github.com/hubmapconsortium/ccf-ui/issues/1139#issuecomment-1769114808)
