### ISSUE TITLE
CCF API /reference-organ-scene endpoint returns too many tissue blocks

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1139]
@bherr2 
When calling https://ccf-api.hubmapconsortium.org/#/operations/reference-organ-scene, e.g., as in https://ccf-api.hubmapconsortium.org/v1/reference-organ-scene?organ-iri=http://purl.obolibrary.org/obo/UBERON_0004539 (= right kidney), we get tissue blocks for many other organs, such as thymus (http://purl.obolibrary.org/obo/UBERON_000237). I assume this is not intended behavior.

**Comment by bherr2** [comment]
Ah! https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-database/src/lib/ccf-spatial-scene.ts#L140 doesn't include the reference organ in the filter.

**Comment by andreasbueckle** [comment]
Awesome! I am using a workaround for now.

**Comment by bherr2** [comment]
@andreasbueckle is your workaround to add ontology-terms= the same organ iri? For instance, this is what the spatial search does with that endpoint when it is loading the female left kidney: 

`https://ccf-api.hubmapconsortium.org/v1/reference-organ-scene?ontology-terms=http://purl.obolibrary.org/obo/UBERON_0004538&cell-type-terms=http://purl.obolibrary.org/obo/CL_0000000&organ-iri=http://purl.obolibrary.org/obo/UBERON_0004538&sex=female`

Notice that it adds the reference organ's uberon term as an organ-iri AND an ontology-terms argument. There are reasons why this is not done by default. If you can do this in your code, that is preferable at this time.

**Comment by andreasbueckle** [comment]
The workaround right now is to loop through the tissue blocks and check if the ```ccf_annotations``` contain the UBERON ID of the organ. That works fine. Thanks!
