### ISSUE TITLE
Enable alternatives to `Inter`/Google Font dependency

### ISSUE THREAD

**Issue by NickAkhmetov** [hubmapconsortium/ccf-ui#1148]
Embedding CCF components currently requires using `Inter`, as the `font-family` is defined as `Inter,sans-serif`.

This could be enhanced by adding a CSS variable to the `font-family` list, which would allow:
- Using `Inter Variable` instead of loading the additional Google Font;
- Using alternative font families in order to better match the rest of the site's styles
  - If an embedder's site uses e.g. `Lato`, the mismatches in font styles don't look great

**Comment by bherr2** [comment]
@axdanbol any thoughts on how we could support something like this?

**Comment by NickAkhmetov** [comment]
Demo of my suggested approach: https://stackoverflow.com/questions/53846582/can-i-use-css-variables-in-a-font-list-and-have-it-work-in-legacy-browsers

**Comment by bherr2** [comment]
Hi @NickAkhmetov we won't be able to deliver on this one for the Dec 15th release. Can you suggest css changes for the hubmap theme that would get them inline with the data portal site? I assume that's the goal here.

We will work on a more general purpose solution in the new year, but for this year, we can either modify the hubmap theme or create a new theme for you.

**Comment by NickAkhmetov** [comment]
Hi Bruce!

My suggestion here is to add a CSS variable that external embedders can use to specify overrides for the default `Inter` font. [i.e. changing this line should do the trick to enable support for fonts other than Inter:](https://github.com/hubmapconsortium/ccf-ui/blob/ab33fa352de24f5bfc57fc16d6a30cbfe373abc5/projects/ccf-eui/src/styles.scss#L131)

Current:

>   font-family: Inter, sans-serif;

With full external font-family support by specifying font names in the `--ccf-ui-font` variable:

>   font-family: var(--ccf-ui-font), Inter, sans-serif

Another solution that would solve the ask in the context of the Data Portal:

>   font-family: Inter, Inter Variable, sans-serif

---

This is motivated by the Data Portal's use of `Inter Variable`, which is the same `Inter` font that is currently used by the CCF UI, but without the need to specify and download each weight of the font separately. [Variable fonts are widely supported](https://caniuse.com/?search=variable%20fonts) and do not present any compatibility issues.

e.g.: https://fonts.google.com/specimen/Inter vs. https://rsms.me/inter/#variable

Since we use Inter Variable throughout the site, any pages where we currently embed the CCF UI require the additional Google Fonts CDN embed. This is not ideal, as 
1. It is redundant with the `Inter Variable` font that users already have from the rest of the data portal
2. Using Google Fonts introduces some unintentional [tracking/privacy concerns which have found standing in German court](https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/).

**Comment by bherr2** [comment]
Ok, sounds good. We'll go with the last solution for now and then try for something more flexible next year!

**Comment by bherr2** [comment]
I'm moving this milestone to our 2024 milestone list, but do check [staging](https://github.com/hubmapconsortium/ccf-ui/tree/staging) tomorrow to see if the simple fix works for now.

**Comment by bherr2** [comment]
We added `var(--ccf-ui-font)` you can customize beyond Inter and Inter Variable @NickAkhmetov

**Comment by NickAkhmetov** [comment]
@bherr2 Thank you!
