### ISSUE TITLE
EUI feature request + There should be MANY more skin Tissue Datasets

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1164]
From @katyb:

@bherr2 
Please add 2 more lines in top right of below so people know #papers and #RUI locations.
Should then look like:
         2      Publications
         2      Tissue Data Providers // GTEx and GE   <- Dan/Andi, add this to RUI MASTER as a column?
![thumbnail_image004](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/105b2d23-2d21-4e6e-b1ab-a6ccb4caa15a)
       Xx      RUI Locations // soon renamed to RUI files??
![thumbnail_image002](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/d1f3bb18-f2f0-4e05-8cda-2bf857b4a958)

Do you need @libby-maier to mock this up?

 Note that the other publication is [https://www.science.org/doi/10.1126/science.abl4290](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.science.org%2Fdoi%2F10.1126%2Fscience.abl4290&data=05%7C01%7Cabueckle%40iu.edu%7C5ec8d018f90a45cb9d2308dbd9ea0dfa%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C638343371506881011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LMyQz6rQui1oKyuPn34QFip7BBtLDGKIJyI4hTU9hA8%3D&reserved=0) by GTEx.

There should be MANY more Tissue Datasets. Please check.

We have data for male and female skin [https://portal.hubmapconsortium.org/organ/skin](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportal.hubmapconsortium.org%2Forgan%2Fskin&data=05%7C01%7Cabueckle%40iu.edu%7C5ec8d018f90a45cb9d2308dbd9ea0dfa%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C638343371506881011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K82%2Bd4iAVHcZmd4yc4NGp%2BnYeDPvaECMfmOCG0FOFFU%3D&reserved=0) locations published in [https://www.nature.com/articles/s42003-023-04991-z](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fs42003-023-04991-z&data=05%7C01%7Cabueckle%40iu.edu%7C5ec8d018f90a45cb9d2308dbd9ea0dfa%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C638343371506881011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oXM%2BpDj8Rck9hKbg%2FkRZ9XfpCoWCYPQan0LyqFKgjsY%3D&reserved=0) generated by GE team.

![Untitled](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/e438787c-ab50-40f8-95d1-8ec3bd2f3084)

**Comment by bherr2** [comment]
* Should we use "Extraction Sites" instead of "RUI Locations"?
* What is the expected # datasets and why?

**Comment by andreasbueckle** [comment]
Yeah, I think we agreed that we should use Extraction Site instead of RUI Locations.

**Comment by bherr2** [comment]
The additional aggregates will be added to the HRA-API
