### ISSUE TITLE
WASDQE annotations and functionality disappears after Review and Download button was pressed

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1189]
Tested on Chrome. When the Review and Download button was pressed, the WASDQE annotations in the top right corner of the 3D view disappear, see below. The keys do not work anymore either.

PS: Not an issue when user loads an existing RUI JSON.

![image](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/14160042-5279-42c2-a787-f090005ba911)

**Comment by edlu77** [comment]
Fixed in develop
