### ISSUE TITLE
ORCID entry in modal validation seems buggy

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1190]
When entering my ORCID into the modal, I get: 
![image](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/9405eb38-46a9-4ecb-8504-02e862284e26)

When I enter it as a URL, it somehow auto-formats it to: 
![image](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/4bad2869-e41d-465e-a8c5-1e186fc0267a)

**Comment by edlu77** [comment]
The form should only take numbers as valid input. Do some ORCIDs have letters as well? I can change that if that's the case.

The form doesn't support url entry right now, only numbers are valid.

**Comment by andreasbueckle** [comment]
OK! Yes, some have numbers, including mine and Dan's, for example.
