### ISSUE TITLE
Upload button in Ingest Portal RUI disappeared

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#1215]
While demoing this on Firefox today, the button to upload an existing RUI location seemed to be gone.

![image](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/d79105be-5ac5-487d-8a14-ac1208f14a8f)

**Comment by bherr2** [comment]
It was moved to the "Registration Metadata" area
