### ISSUE TITLE
As a researcher I need to see a logo so that I know the app is part of HuBMAP.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#128]
Ensure the researcher knows they are in a HuBMAP tool by:

- [x] Placing a persistant HuBMAP logo in the top left of the Logo Bar in the UI that has strong contrast with the background.
- [x] The native tooltip that appears on hover should show the title text: HuBMAP (Human Body Molecular Atlas Project).
- [x] Linking the logo to the default, aside panels open and torso active with organs overlaid, view.
- [x] Showing the logo is clickable by having the logo have an animated change to blue on hover with a pointer that is a finger to indicate a link.
- [x] Providing a click action that takes the user back to the default state of the tool.

**Comment by adphillips2017** [comment]
Should pressing this button reset reset the user's filters?

**Comment by lecross** [comment]
Good question. It is meant as a Home button action. It is not meant as a reset action. It is logical that the user would return to the default state to pursue another path through the data but want to retain the filters. While it is also logical the user would want a clean slate, the previous is the more likely scenario.
