### ISSUE TITLE
As a researcher I need to know what data is available in the tool and a means to download it so that I work with the data.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#129]
Ensure the researcher can work with the data by:

- [ ] Providing dynamic data at the top right below the Nav Bar of the right drawer that covers Sex, Age, BMI
- [ ] A yellow-orange download icon that is clearly visible
- [ ] The native tooltip that appears on hover should show the title text: Downlown Data Set
- [ ] The download icon should on hover change to blue and have a finger cursor to indicate it is a link
- [ ] Providing a download icon that launches the download
- [ ] Providing a download of the data that is in a usable (requested) format
- [ ] Providing a download that opens in the researcher’s tool of choice
- [ ] Providing the ability to cancel the download before or during
- [ ] Providing the ability to name the download file and choose the destination

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
