### ISSUE TITLE
As a <researcher> I need <to give feedback> so that <I can help improve the tool>

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#13]
Ensure the researcher can navigate to the main HuBMAP project site by providing:

* [x] the Comments logo at the bottom left of the screen with a link that opens the Google Forms Feedback form in a new window.

**Comment by bherr2** [comment]
@lecross what is the URL for the feedback form for the CCF UI?

**Comment by lecross** [comment]
https://forms.gle/9U1HVpQANyuHn97M8

**Comment by bherr2** [comment]
@lecross Email address is on there twice :-O
