### ISSUE TITLE
As a researcher I need to adjust the gender so that I can find data that I want to work with related to either male, female, or both.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#138]
Ensure the researcher can find the sex adjusted data they want to work with by:

- [x] Providing a dropdown input labeled SEX that shows the currently active selection in blue
- [x] Providing on click a list of available options for sex: both, female, male (NOTE: for inclusion purposes, lets use this order); the list should animate open, ease in-out
- [ ] Showing the active item in the list with a bar at the left and checkmark at the right
- [x] Adding a drop-shadow to the background of the list items in the dropdown to separate it from the Filter Flyout and items that fall beneath
- [ ] Providing a click action that when the user makes a selection, the new active selection gets the bar at the left and the check box at the right, and that the previous selection returns to the default state without them
- [x] Providing a finger pointer cursor on hover of the dropdown and the list in the dropdown
- [x] Providing an animated close action (ease in-out) following clicking on a new sex or on mouse-out

**Comment by edlu77** [comment]
What is the bar at the left and the check box at the right? I don't see anything like that on the UI.

**Comment by bherr2** [comment]
@lecross can you provide some clarity on Acceptance Criteria 3-5 (the unchecked items in the list above)?
