### ISSUE TITLE
As a researcher I need to filter by a specific TMC so that I can find data that is relevant to my research.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#142]
Ensure the researcher can find the TMC filtered data they want to work with by:

- [x] Providing a section on the Filter Flyout labeled Tissue Mapping Center (TMC)
- [x] Providing a list of TMC related items with checkboxes
- [x] Providing inactive checkboxes a state with empty squares and when selected, an active state with a blue fill and a white checkmark
- [x] Providing the researcher the ability to check/uncheck options as needed

**Comment by bherr2** [comment]
Styling is off for the checkboxes (should be blue background and white check when selected). Were there issues in making this happen?
