### ISSUE TITLE
As a researcher I need controls to interact with the sample image on the Stage so that I can more easily make judgements about what I am seeing.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#150]
Ensure the researcher has controls for interacting with the sample image on the Stage by:

- [ ] Providing on hover controls at the top left and right of the stage
- [ ] Providing at the top right of the stage an icon that on click makes the Stage full-screen, updating the icon by changing it to the close full-screen icon. The full-screen expansion should be animated
- [ ] Providing two two groups of controls on the left top of the Stage
    - [ ] Group 1: A plus icon that on click zooms the Stage in. A minus icon that on click zooms the Stage out. Both actions zoom the Stage and update the PIP by sizing the yellow box that overlays a thumbnail copy of the Stage image at 100% to represent the Stage as viewed by the researcher. The Scale text at the bottom left will update to reflect the current resolution.
    - [ ] Group 2: If more than one item is in the group a stack of three dots will indicate that more options are available. On click, the bar will expand to the right and the icon will change state. The Reset icon is the first in the group and on click returns the Stage to the default state of the sample at 100%. Scale updates accordingly. NOTE: Currenlty, only the Reset icon will appear.
- [ ] Providing zoom-in/zoom-out using the scroll-wheel on the mouse. Scale and PIP updates accordingly.
- [ ] Providing drag option where the user can click, hold, with the mouse and drag the Stage contents around to see other areas. PIP updates accordingly.
- [ ] Providing a PIP that helps to orient the user to where they are on the original sample as they change zoom. The user can use the yellow box in the PIP to move to other locations, the Stage updating accordingly as the researcher drags the box.
- [ ] Providing a persistent scale that changes as the user zooms in/out

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
