### ISSUE TITLE
As a researcher I need to have in the TV a way to see cells, gross anatomical structures, and technologies  so that I can find information about the sample that I’m looking for.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#154]
Ensure the researcher has in the TV a way to see cells, gross anatomical structures, and technologies so they can get more information about the sample by:

- [x] Providing a toggle for Layers
- [ ] Providing inside the Layers toggle a list all available cells, anatomical structures, and technologies
- [x] Providing inside the Layers toggle a checkbox for each item in the list that when clicked, showing the standard blue background with white checkmark to show as active, will update Stage with the respective overlay
- [ ] Providing the ability to layer overlays on Stage so the user can see interrelationships between items selected from the list.

**Comment by bherr2** [comment]
https://github.com/hubmapconsortium/vitessce-image-viewer/blob/master/demo/src/source-info.js
http://viv.vitessce.io/
