### ISSUE TITLE
As a researcher I need to add a color scheme so that I can give meaning to individual items in the Layers toggle.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#156]
Ensure the researcher can add a color scheme to give meaning to items in the Layers toggle by:

- [ ] Providing a dropdown that shows the active color scheme
- [ ] Providing a dropdown that when clicked opens to show the list of available color schemes with radio buttons to the left for selecting only one at a time
- [ ] Providing radio buttons that show as an empty gray outline when inactive and with a blue background with white center circle when active
- [ ] Providing a dropdown that closes when the user mouses-out or clicks-out of the dropdown
- [ ] Providing color indicators that appear next to items selected in the list of available overlays in the Layers toggle
- [ ] Providing a default color scheme
- [ ] Providing colors assignments as the user adds items in the following manner: first left, first right, center, second left, second right, third left, third right

**Comment by adphillips2017** [comment]
@lecross Does changing the brightness / transparency count as a customization in regards to automatically reassigning colors when changing overall color scheme?

**Comment by lecross** [comment]
No. Whatever the color assignment, if they adjusted the brightness or transparency, it applies to the new color/gradient.
