### ISSUE TITLE
As a researcher I need use the visual body UI so that I can find the organ and sub-structures I want to work with.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#160]
Ensure the researcher can use the visual body UI to navigate to an organ and substructures by:

- [ ] Providing the human torso with clickable organs overlaid
- [ ] Providing hover action when a researcher mouses over the organ, making it grow by 5%
- [ ] Providing on hover over an organ an update to the information at the top of the Tissue Browser Drawer
- [ ] Creating a pre-defined zoom in on an organ if it is clicked, such that other organs are removed and it is centered on Stage; and updating the text above the TB to have the organ specific information as far as counts. This new zoom level will include cuboids on the organ.
- [ ] Providing the ability for the user to click on one of two organs in a pair, such as left and right kidney, to only see that one organ. The Stage will center on the one organ. The other will have its opacity reduced so that it is hinted at, thus providing context (assuming the zoom level allows for its being viewed).
- [ ] Providing the user the ability to click and drag the Stage to reposition or to provide the ability to click on the other organ in a pair. NOTE: This assumes that we continue to not what the user pulling from the two organs simultaneously.
- [ ] Providing the user the ability to zoom in further by clicking anywhere on the organ that is not covered by a cuboid. The user can also use the mouse scroll-wheel to zoom in and out, however the focus will remain the centered organ.
- [ ] Providing a text update to the right drawer above the descriptive text and updating the dynamic values in that text accordingly

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
