### ISSUE TITLE
As a researcher I need use the visual body UI so that I can use cuboids to sub-structures I want to work with.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#161]
Ensure the researcher can use the visual body UI to navigate cuboids to find sub-structures by:

- [ ] Providing cuboids that are white at alpha 30%, with white borders at 100%, that are positioned on the organ at the point where the slabs were registered in the RUI
- [ ] Providing cuboids that on hover will update the text in the TB to reflect associated counts
- [ ] Providing cuboids that on click go from white to blue at the same alphas
- [ ] Providing cuboids that by clicking on more than one become a larger selection and update the text in the TB accordingly
- [ ] Updating the ontology. When a cuboid is selected, it is assumed that the user is drilling down through the ontology. Thus, all terms in the ontology that are tagged for the cuboid will become blue, expanding to reveal and sub-terms that are related

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
