### ISSUE TITLE
As a researcher I need to download the data set on the TV so that I can use work with the data locally.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#162]
Ensure the researcher can download data on the Tissue Viewer page by:

- [ ] Providing dynamic data at the top right below the Nav Bar of the right drawer that covers Sex, Age, BMI
- [ ] The native tooltip that appears on hover should show the title text: Downlown Data Set
- [ ] The download icon should on hover change to blue and have a finger cursor to indicate it is a link
- [ ] Providing a download icon that launches the download
- [ ] Providing a download of the data that is in a usable (requested) format
- [ ] Providing a download that opens in the researcher’s tool of choice
- [ ] Providing the ability to cancel the download before or during
- [ ] Providing the ability to name the download file and choose the destination

**Comment by adphillips2017** [comment]
@lecross Where is the TV download button going?

**Comment by lecross** [comment]
There are multiple download buttons. There is the one associated with the larger data set and one associated with an individual sample. These all go to the same location but have different parameters around what data is downloaded. They go to Globus. Bruce is the person specifying the location they go to. I have no information. We are relying on the external partner to handle providing the functionality for the download. Bruce will also know how the link needs to be constructed.

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
