### ISSUE TITLE
As a researcher I need to see a view that contains all the organs, or just one organ so that I can explore other organ options.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#163]
Ensure the researcher can download data on the Tissue Viewer page by:

- [ ] Providing the ontology terms at the organ and body level to act as breadcrumbs back up the zoom levels. Such that clicking BODY will return the user to the default Stage with the torso and all organs; clicking the term heart would make the heart the active organ centered on the stage. Text and the Tissue Browser list will update accordingly.

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
