### ISSUE TITLE
Brightness Change Removes Tiled Layer

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/ccf-ui#249]
I have noticed that while using the brightness sliders, the tiled layer disappears.  I can't upload a video but @bherr2 can share it with whomever tackles this.  If you compare https://portal.hubmapconsortium.org/ccf-eui to [viv.vitessce.io](http://viv.vitessce.io) (for example) you can see this when you use the sliders.

**Comment by bherr2** [comment]
We are dropping viv in the EUI (we'll just link out to the portal visualizations)
