### ISSUE TITLE
As a researcher I need to in the Ingestion Portal modal that contains the app have a means to close the modal so that I can return to the Portal to add another registration or other task

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#264]
Ensure the researcher can get back to the Ingestion Portal by:

* Providing a BACK button in the Logo Bar
* Closing the modal when the user clicks the BACK button and revealing the Ingestion Portal that the modal overlays
* Providing a chevron icon that points to the left and the text "BACK"

Original ID: 3

**Comment by bherr2** [comment]
How do I test that this work?

**Comment by axdanbol** [comment]
Good question. I probably have to add some way to do so. Also what is the url that it should return to?

**Comment by bherr2** [comment]
The URL will be provided in the global config object (assuming we do the same we did with EU) or environment.ts. But as far as where it should point in testing? `/` should do which effectively does the same as clicking the logo now.

**Comment by axdanbol** [comment]
Ok, to switch between them currently you have to change the PageState and set embedded to true. There you can also update the url to which it points.
