### ISSUE TITLE
Create template application (projects/ccf-rui)

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#289]
Original ID: 29

**Comment by bherr2** [comment]
This wasn't fleshed out originally, but one thing we need is to have a visual inspection of the state so that we know all this stuff we're hooking up is actually hooked up. As discussed at stand-up today, let's use the center stage to have a debug component that will display at least all of the state necessary for the 3d placement component, but potentially more just to make sure things are _actually_ wired up.

**Comment by axdanbol** [comment]
I'm currently working on this component + state.
