### ISSUE TITLE
As a researcher I need to select an extraction set because I need to work with a spectific set of extraction sites for registering my data.

### ISSUE THREAD

**Issue by lecross** [hubmapconsortium/ccf-ui#339]
Ensure the researcher can select extraction sets to select the ones needed for registering their data by:

- Adding a select drop-down directly beneath the section header Common Extractions Sites
- Have as placeholder text on the select the words "Extraction Sets"
- When the user clicks on the select the list of available sets appears using the standard style for Angular Materials
- When the researcher hovers over items a gray background indicates the one with focus
- When the researcher selects an item the gray background stays behind the item to show which is selected and the list of extraction sites appears below the drop-down with visibility icons on the left in the default state for "not visible"
- The Extraction Sets drop-down only appears in Common Extraction Sites if more than one set exists, otherwise the extraction sites list will show in the section
- The list of items in the select include a descriptive label and the number of sites
- Current list items for the heart are: HuBMAP (10), SPARC (15), HCA (6)

**Comment by bherr2** [comment]
@lecross what happens when they select one or more items from multiple extract sets? Do they show all or just from the currently selected extraction set?

**Comment by lecross** [comment]
Correct me if I'm misunderstanding the question. When the user clicks on Extraction Set a list of sets appears in the drop-down select. When the user chooses a set from the drop-down select, the list of available options appears below the element as results. These options load in the invisible state (gray eye icon, no green blocks on stage). When the user selects the gray eye icon, it turns blue, and the corresponding block appears on stage. Per Katy's design, the user can select multiple extraction sites to be active at one time. The user cannot select multiple sets. Changing sets removes active sites from the stage. In effect, changing sets resets the stage.

**Comment by bherr2** [comment]
Yep, that answers our question. The stage should only reflect the currently selected extraction sites from the currently selected selection set.

**Comment by lecross** [comment]
That is correct based on my understanding.
