### ISSUE TITLE
As a researcher when using the RUI interface sections sometimes get longer and I need scrollbars to make content manageable.

### ISSUE THREAD

**Issue by lecross** [hubmapconsortium/ccf-ui#340]
Ensure the researcher has scrollbars to make page content manageable by:

- Providing a scrollbar for each drawer that will appear if the total content for the drawer exceeds the view
- Providing a scrollbar for individual sections (e.g. Extraction Sites) for when the count goes above eight (8) items in the list
- Providing a scrollbar for the Tags section for when the number of tags goes beyond four rows

**Comment by bherr2** [comment]
Be sure to address some of the feedback we got from lecross when finishing this user story:
* There is a strange behavior with content in the drawers. If I size from bottom things move up to cover other items. Hopefully the drawer scrollbar will fix this.
* NEW: White dividers should not span the drawer anymore. When the drawer scrollbar appears this will cause issues. No scrollbar currently appears. I’m seeing that the section scrollbars align with the right edge. The drawer scrollbar will need to align with the right edge as well to put space between them.
