### ISSUE TITLE
Tick marks on rotation slider are too small

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#349]
* Rotation slider knobs are now circular. Animation of slider is good. Tick marks are present but too small. Near invisible.

**Comment by bherr2** [comment]
@lecross the tick marks are the default size according to Angular Material. We tried messing with the styling on that component for another thing and it was quite painful. Do you want us to still try and customize this?

**Comment by lecross** [comment]
Yeah, it is one of those stylistic issues. Per agreement, we are sticking with defaults for now. I'm not a fan of the style as it is near invisible.
