### ISSUE TITLE
As a researcher I need to have the stage nav minimize space usage when the screen size is constrained so that I can still use the stage effectively

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#350]
Ensure the researcher can still use the stage effectively on a small space by:

* Putting stage top nav into a hamburger menu when constrained for space

**Comment by lecross** [comment]
That was simply me expressing an opinion. That's the reason it was phrased like it was. It is not approved. Simply progress based on the agreed upon spec.

**Comment by bherr2** [comment]
Ok, its not scheduled for implementation this sprint. If you want to add it in the next week or two, it can possibly go into the last sprint.
