### ISSUE TITLE
Tooltips on Landing

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#415]
When first landing on the page, I would expect a button that lets me "click away" all the tooltips (like the "Got it" button on Google products). Instead, they only disappear when I select an organ. This is not intuitive.

**Comment by andreasbueckle** [comment]
BH: That was kind of in the original spec, which says "any interaction", but there is a problem with that when trying to differentiate behaviors between embedded and standalone versions. We could address this in the next round of specs.

**Comment by bherr2** [comment]
@lecross any comments?

**Comment by lecross** [comment]
Bruce,


I'm focused on trying to get SciMaps done. If I can get the spec into draft today, I'll take a look tomorrow.



________________________________

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
