### ISSUE TITLE
Reference system origin marker

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#417]
Would it make sense to include an origin marker for the 3D ref system? Otherwise, it could be hard to understand what x, y, z-location these coordinates are in reference to.

**Comment by andreasbueckle** [comment]
BH: Possibly, perhaps in the next round of specs?

**Comment by bherr2** [comment]
@lecross any comments?

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
