### ISSUE TITLE
Preview mode: why reset camera?

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#419]
When in Preview mode, zooming in, panning, and rotating works great. Then when I change the size or the rotation, the camera zooms back out and makes this task harder. I wish this did not happen. It is super useful to be zoomed in when adjusting rotation and size.

**Comment by andreasbueckle** [comment]
PS: I just gave an impromptu demo of the RUI v1.0 and wanted to share my impression.

**Comment by bherr2** [comment]
It was decided not to allow it in non-preview mode. We can/should consider it for a future revision. @lecross

**Comment by andreasbueckle** [comment]
Clarification:
The camera resets when I change the size or rotation *while still in preview mode*. This invalidates the usefulness of the camera in preview mode. Our user studies indicate (upon initial review) that many users value the possibility to zoom in when rotating the tissue block. Resetting the zoom automatically in the RUI v1.0 then has an adverse effect and makes the rotation tasks harder.

**Comment by bherr2** [comment]
Oh, I see. That doesn't happen in my browser. What browser/version/os are you using?

**Comment by bherr2** [comment]
Ahh, I see that now. Changing this to a bug report.
