### ISSUE TITLE
3D preview cam too restricted

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#429]
It appears that the orbit camera movement is too restrictive for some heart SMEs. Most other organs in the RUI are fairly vertical, so having full freedom to rotate around the organ's y-axis only makes a lot of sense. But we currently restrict the rotation around what I assume is the organ's x-axis quite severely, making it heart to "fly" on top of the heart, which prohibits him from getting a better view of certain extraction sites. Not sure how much work this is to override as I assume this is standard deck.gl orbit cam behavior.

**Comment by bherr2** [comment]
There is 15 degrees of X axis rotation which was part of the spec. I think its reasonable to increase that, but to what? CC: @lecross @katyb

**Comment by andreasbueckle** [comment]
I would say 45 degrees sounds good (as in 45 degrees up and 45 degrees down for a range of 90 degrees). Triple of what we have right now sounds like a good choice.

**Comment by andreasbueckle** [comment]
@bherr2 How soon would you be able to implement this? Would like to let our user know.

**Comment by bherr2** [comment]
Assuming we get buy-in from @katyb and @lecross before then, we can probably add it early next week.

**Comment by lecross** [comment]
Andreas and Katy are lead on RUI. Go with what they determine. Cheers!

**Comment by andreasbueckle** [comment]
@katyb 
Please let me know what you decide so I can inform Marc about the change.

**Comment by andreasbueckle** [comment]
@bherr2 I suggest we go ahead and implement 45 degrees (as in 45 degrees up and 45 degrees down for a range of 90 degrees). Marc is ready to register a ton of tissue and it sounded like this would be a small change to make. Thanks.

**Comment by bherr2** [comment]
Ok, I'll prioritize that work for early next week. It should be able to be pushed to the standalone site pretty quickly.

**Comment by bherr2** [comment]
Fixed and available at https://hubmap-ccf-ui.netlify.app/rui/
