### ISSUE TITLE
Tooltips text boxes not responsive

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#432]
Got an inquiry from a user about how the tooltip text boxes on load are not responsive. When the browser window is "squished", the website thus looks buggy:

![image](https://user-images.githubusercontent.com/22821046/102628494-c2039500-4117-11eb-999a-29ee9d309c03.png)

**Comment by bherr2** [comment]
Superseded by revisions in the v1.5.0 spec.
