### ISSUE TITLE
As a researcher I need to have access to Help so that I can better work with the app.

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#449]
Ensure the researcher has access to Help to better work with the app by providing:

* In the Right Drawer an icon in Primary blue of the standard Help icon at the top left
* A Help icon that when hovered over indicates it is clickable by showing a gray background and a pointer cursor
* A Help icon that when clicked opens a modal comprised of various topics contained in expansion panels
* A markdown-based system where each H1 header becomes an expansion panel. So there is a single documentation.md that has all the documentation to be shown. Initial md will have an About and Acknowledgements expansion panels.

**Comment by hrishikeshpaul** [comment]
Hi, I wanted to clarify a few things before starting this. Most of the 'functionality' remains the same except each of those bullet points will have their own panels right? I saw the components, and it looks like there are no h1 tags. IS there a documentation.md to look at? I guess it should be fairly simple to create a component and edit the data. Please let me know!

**Comment by bherr2** [comment]
Right, you'll need to create your own documentation.md. If its not already been included you'll want to use https://www.npmjs.com/package/ngx-markdown as the markdown library to use.

**Comment by bherr2** [comment]
And practically, for this pass, you'll have two expansion panels: "About" (ie all the stuff currently above acknowledgements other than the modal title) and "Acknowledgements".

**Comment by hrishikeshpaul** [comment]
Ah, I see. I think I should be able to do it. I saw the documentation and it seems like you can override any element (they showed overriding the blockquote as an example). So I guess h1 -> mat-expansion-panel shouldn't be that hard.
