### ISSUE TITLE
As a researcher I need to see on the Registration Block RGB bars so that I know the axis for correct registration.

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#452]
Ensure the researcher to see Registration Block RGB bars to identify axis for correct registration by providing:

* On the yellow Registration Block in the crosshairs, starting at back lower left, a blue bar for Z-axis, a red bar for X-axis, and a green bar for Y-axis
* The X, Y, Z bars as a static part of the Block, visible against the yellow it is colored
* X, Y, Z bars that have the same colors as the slider controls in the Right Drawer

**Comment by andreasbueckle** [comment]
@bherr2 
Below is a preview of the cube made in Blender. And here is the (GLTF file)[https://drive.google.com/file/d/1pqJn4-2rrmg7SvE_TFQgDyxPJVl-HSHg/view?usp=sharing]. Let me know where to put it so we can test how it looks. 
![image](https://user-images.githubusercontent.com/22821046/139484041-3c14e119-7343-4bc3-8d47-51bf70b739df.png)

**Comment by bherr2** [comment]
When I downloaded the glb this is what I see in Blender:
![image](https://user-images.githubusercontent.com/34098595/139487788-9d7ea624-8156-40d4-908e-dc2da7684122.png)

**Comment by andreasbueckle** [comment]
Thanks. Try this GLTF file instead? If that does not work, I'll look some more into it. 

https://drive.google.com/file/d/1prXO_xqmoEfsGfIFzvF-iANWXpvxdeGU/view?usp=sharing

**Comment by andreasbueckle** [comment]
PS: Here is another take at the GLB version:

https://drive.google.com/open?id=1pqJn4-2rrmg7SvE_TFQgDyxPJVl-HSHg&authuser=abueckle%40iu.edu&usp=drive_fs

**Comment by bherr2** [comment]
Got the cube color now but not the spaghetti pole colors

**Comment by andreasbueckle** [comment]
Try this one. I changed a setting in Blender to export the file with the node settings I prepared for the materials:
https://drive.google.com/open?id=1pqJn4-2rrmg7SvE_TFQgDyxPJVl-HSHg&authuser=abueckle%40iu.edu&usp=drive_fs
