### ISSUE TITLE
Update styling to fit spec

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#490]
Do a pass over the [spec](https://drive.google.com/file/d/1M0Pfu41Kv-RBOvIF9hB-mcNK9U4qsDIp/view) and update styling to match the spec. If there are larger issues to hammer out, let's go over it and possibly spawn into separate issues.

**Comment by hrishikeshpaul** [comment]
## Header

- [ ] Add shadow
- [ ] Replace the info button with a login button

Current: 

![Screen Shot 2021-02-24 at 7 06 24 PM](https://user-images.githubusercontent.com/22999894/109083197-6fc09080-76d3-11eb-94e0-e427a2856401.png)

Spec: 

<img width="1396" alt="Screen Shot 2021-02-24 at 7 06 59 PM" src="https://user-images.githubusercontent.com/22999894/109083228-7e0eac80-76d3-11eb-9be8-8b5f70523232.png">

**Comment by hrishikeshpaul** [comment]
## Left sidebar

- [ ] Change background color to white
- [ ] Change the underline color of the inputs to the primary blue
- [ ] Remove the divider between 'Donor Sex' and 'Name Inputs'
- [ ] Darken the dividers
- [ ] Change color of the mat-toggle to primary blue
- [ ] Add the 'UPLOAD PREVIOUS REGISTRATION DATA' button at the bottom.
- [ ] Change color of the mat expansion panel's expand button (down arrow) to primary blue.

| Current | Spec|
| --- | --- |
| ![Screen Shot 2021-02-24 at 7 07 54 PM](https://user-images.githubusercontent.com/22999894/109083504-0725e380-76d4-11eb-905e-e5485c60434f.png) |  <img width="313" alt="Screen Shot 2021-02-24 at 7 11 13 PM" src="https://user-images.githubusercontent.com/22999894/109083527-1442d280-76d4-11eb-8794-6c128d29904d.png"> |

**Comment by hrishikeshpaul** [comment]
## Stage

- [ ] Add a border radius of 8px to the stage
- [ ] Add padding at the bottom (24px)

Current:

![Screen Shot 2021-02-24 at 7 14 02 PM](https://user-images.githubusercontent.com/22999894/109084068-0fcae980-76d5-11eb-883b-ab911a20c8a2.png)

Spec: 

<img width="832" alt="Screen Shot 2021-02-24 at 7 18 37 PM" src="https://user-images.githubusercontent.com/22999894/109084101-1e190580-76d5-11eb-9b08-9d57993d461f.png">

**Comment by hrishikeshpaul** [comment]
## Stage Radio buttons and toggle

- [ ] Place all of them on the same line

Current: 

![Screen Shot 2021-02-24 at 7 29 00 PM](https://user-images.githubusercontent.com/22999894/109084910-a8ae3480-76d6-11eb-9aaf-d0d55d1778b8.png)

Spec: 

<img width="491" alt="Screen Shot 2021-02-24 at 7 28 54 PM" src="https://user-images.githubusercontent.com/22999894/109084920-ae0b7f00-76d6-11eb-8126-b682827d9497.png">

**Comment by hrishikeshpaul** [comment]
## Right sidebar

- [ ] Change color to white
- [ ] Push Tissue Block Size down, and add the info button as shown in the spec
- [ ] Remove mat dividers 
- [ ] Update the input button in the Anatomical Structure Tags based on the spec
- [ ] Update the REVIEW & SUBMIT button at the bottom to match the spec


| Current | Spec|
| --- | --- |
| ![Screen Shot 2021-02-24 at 7 21 58 PM](https://user-images.githubusercontent.com/22999894/109084601-127a0e80-76d6-11eb-98a0-3f2d88d4e34c.png) | <img width="327" alt="Screen Shot 2021-02-24 at 7 25 18 PM" src="https://user-images.githubusercontent.com/22999894/109084616-1b6ae000-76d6-11eb-9e29-0c1386523d64.png"

**Comment by hrishikeshpaul** [comment]
## Drawer Tabs
 
- [ ] Change icon of the drawer tabs to the triangle as shown in the spec

<img width="327" alt="Screen Shot 2021-02-24 at 7 31 07 PM" src="https://user-images.githubusercontent.com/22999894/109085014-ddba8700-76d6-11eb-854e-744fbc91f483.png">

**Comment by hrishikeshpaul** [comment]
@bherr2 I went through the spec and compared it with the current version of the RUI. I'll use this issue to keep track of all the changes that need to be made. Please feel free to update/comment incase I've missed something out

**Comment by bherr2** [comment]
> ## Right sidebar
> 
>     * [ ]  Change background color to white
> 
>     * [ ]  Push Tissue Block Size down, and add the info button as shown in the spec
> 
>     * [ ]  Remove mat dividers
> 
>     * [ ]  Update the input button in the Anatomical Structure Tags based on the spec
> 
>     * [ ]  Update the REVIEW & SUBMIT button at the bottom to match the spec
> 
> 
> Current 	Spec
> ![Screen Shot 2021-02-24 at 7 21 58 PM](https://user-images.githubusercontent.com/22999894/109084601-127a0e80-76d6-11eb-98a0-3f2d88d4e34c.png) 	<img alt="Screen Shot 2021-02-24 at 7 25 18 PM" width="327" src="https://user-images.githubusercontent.com/22999894/109084616-1b6ae000-76d6-11eb-9e29-0c1386523d64.png">

Check the latest merge regarding the Anatomical Structures Tags section on the right. Daniel should have it mostly to spec.
