### ISSUE TITLE
Add bilateral organs as separate items in the carousel

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#494]
The carousel should now show left/right versions of each bilateral organ. So, there should be a Left Kidney and Right Kidney rather than a single Kidney option.

Assets: [icons-organs.zip](https://github.com/hubmapconsortium/ccf-ui/files/6029410/icons-organs.zip)

**Comment by bherr2** [comment]
Updated organ icons are attached here:
[icons-organs.zip](https://github.com/hubmapconsortium/ccf-ui/files/6029309/icons-organs.zip)

**Comment by lecross** [comment]
Added left & right lung icons to the organ icon set.
[icons-organs.zip](https://github.com/hubmapconsortium/ccf-ui/files/6029410/icons-organs.zip)
