### ISSUE TITLE
Update EUI styling to fit spec

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#508]
Do a pass over the [spec](https://drive.google.com/file/d/15mx__aHeNDCBBYBXM64ED6YAOeyp9Fcy/view) and update styling to match the spec. If there are larger issues to hammer out, let's go over it and possibly spawn into separate issues.

**Comment by hrishikeshpaul** [comment]
## Header
- [ ] Change logotype
- [ ] Remove sex, age, bmi and the 3 buttons
- [ ] Refactor the button to match spec
- [ ] Add a shadow to the header

Spec: 

![Screen Shot 2021-03-01 at 7 24 13 PM](https://user-images.githubusercontent.com/22999894/109577582-d4109500-7ac3-11eb-8f74-fba75b49dd80.png)

Current:

<img width="1438" alt="Screen Shot 2021-03-01 at 7 24 17 PM" src="https://user-images.githubusercontent.com/22999894/109577592-d96ddf80-7ac3-11eb-8ba4-9986f2a9b9cd.png">


## Toolbar
- [ ] On the left sidebar there should be Filter, Sex, Age, BMI 
- [ ] Organ Selector in the middle (guessing Edward is adding that)
- [ ] On the right sidebar there should be Full Screen, Dark/Light mode selector, refresh  and info
- [ ] Fix size of icons

Spec:

![Screen Shot 2021-03-01 at 7 25 48 PM](https://user-images.githubusercontent.com/22999894/109577772-2d78c400-7ac4-11eb-9519-950064d99141.png)

Current: 

<img width="1432" alt="Screen Shot 2021-03-01 at 7 25 42 PM" src="https://user-images.githubusercontent.com/22999894/109577804-38cbef80-7ac4-11eb-8467-11bc8f1ec390.png">


## Search

- [ ] Update search bar style to match spec

Spec: 
![Screen Shot 2021-03-01 at 7 28 24 PM](https://user-images.githubusercontent.com/22999894/109577871-58fbae80-7ac4-11eb-8809-48f92f2f1df9.png)

Current: 
<img width="425" alt="Screen Shot 2021-03-01 at 7 28 56 PM" src="https://user-images.githubusercontent.com/22999894/109577892-62851680-7ac4-11eb-8e32-53293d8dde9b.png">

## Stage
- [ ] Add border radius to stage

Spec:
![Screen Shot 2021-03-01 at 7 29 36 PM](https://user-images.githubusercontent.com/22999894/109577955-8183a880-7ac4-11eb-85a4-d698973807a1.png)

## Sidebars
- [ ] Change background color to white

**Comment by hrishikeshpaul** [comment]
## Drawer Tabs Icons

- [ ] Change drawer tab icon to fit spec
