### ISSUE TITLE
Opacity sliders hidden by unintuitive and burdensome interaction

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#527]
IMO, getting to and using the opacity sliders inside the expanded AS accordion menu is a chore. Having to hover over the little drop icon is tiring. Would it be possible to let the user access the slider when hovering just over the AS text?

**Comment by bherr2** [comment]
@lecross ?

**Comment by lecross** [comment]
There are repercussions. As the user interacts with the list the hover state will trigger as they move over the list. Do as you think best meets user needs.

**Comment by andreasbueckle** [comment]
My gut feeling is that most users will not use the opacity sliders at all now that 20% is the default opacity. Even less will turn structures on and off, because it is such a hassle even getting to the toggle. 
Do we log any user interactions? Would love to see how much these interactions are being used.
