### ISSUE TITLE
Button should say Submit

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#562]
This may have been fixed by now, but I noticed that when accessed from within the ingest portal, the blue button in the bottom-right still says Review and Download rather than Submit. Is that on purpose?

**Comment by bherr2** [comment]
Yes, that is most definitely a bug. Leonard will be sending an updates doc soon that we'll roll this into.

**Comment by bherr2** [comment]
It now says Review and Register on the ingest portal
