### ISSUE TITLE
RUI - QA 3

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-ui#568]
- [x] The tooltips for FName, LName, Donor, AS all sit too far below the item they reference. 1rem to 1.5rem is about right.
- [x] Starting state looks correct. All three toggles are open.
- [x] There is an issue with uniformity of grays. Placeholder/explainer/label text should all be the same. Discrepancies: explainer text for AS, CES is not the same as for Tags; FName, LName is not the same as Tag Search; FName, LName are not the same as Thickness, #Slices; elevated labels on FName, LName are not the same as other inputs. All should be #CCCCCC.
- [x] Previously Registered Blocks chip should show disabled icon, the icon is currently missing at default.
- [x] For bold headers, make them the same bold weight as in EUI. Either use 600 or 700 weight.
- [x] Tag Search. Would prefer the button for Plus extend from top to bottom of input and to the right edge. It should represent a square section of the input.
- [x] Tooltips between EUI and RUI should have the same look and the same spatial relationship to trigger element. I recommended 1rem to 1.5 rem in the EUI. Whatever is chosen should be consistent between the two. 1rem seems enough.
- [x] Donor Sex cursor state is showing for the label but not the slider. Needs to show for the slider.
- [x] RUI & EUI, the close button in the top right of the Help needs to have a hover state. Missed this when going through EUI. Also, use the drop-shadow style from EUI for RUI. RUI is incorrect. Both modals should have a drop-shadow to lift it off the content below.
- [x] RUI & EUI. Icon hover states should animate in and out.
- [x] RUI & EUI. The Search inputs should be the same height and colors. Use the same height, both should be 48px tall. RUI is incorrect.
- [x] Opacity icons on hover should see cursor change to pointer. This is for consistency. IF this conflicts with the control bar then don't worry about it.
- [x] Opacity control. Slow the animation on/off. Note the difference in speed between the control and the reset button.
- [x] The R Drawer resets don't have the same hover state as the one in AS. All should have the same color as well. Use the AS, CES as master.
- [x] Tag Search. When a result is selected, the Plus should show the gray background as indicator that it is the next action.
- [x] Tag Search. When an item is added, the Search area should return to default. Currenlty the result counter is keeping the input expanded. The counter needs to be removed on Add and the input state set to flat.
- [x] Scrollbars for AS and CES. I'm seeing them, but they are present regardless. Originally the intention was that after like six items the scrollbar would appear. Here I'm seeing it with one item.
- [x] Scrollbars. Reset should not be in the scroll field. The scrollbar should only advance AS/CES list items.
- [ ] Register/3D Preview have an issue. The human form on the right, we call it the gismo, should be oriented to the position of the organ. Instead, it is relative to the 3D Preview. Thus, going from that back to Register shows the gismo oriented incorrectly. Since the gismo is not needed in Register mode, it should likely be removed for now from that view.

**Comment by hrishikeshpaul** [comment]
> Previously Registered Blocks chip should show disabled icon, the icon is currently missing at default.

What is the disabled icon?

**Comment by bherr2** [comment]
@lecross ?

**Comment by lecross** [comment]
The Previously Registered Blocks chip has a few components: an outline button, button text, and an icon at the left. All three things exist whether the button is in ready state (the user can interact) and disabled state (the user cannot click and the cursor indicates that they can't). In the disabled state, the icon, like the rest of the button, is grayed out. The icon was not present in the disabled state and should be.
