### ISSUE TITLE
EUI QA 3

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-ui#569]
Global

- [ ] Counted 5 sec for initial load. The blue bodies took longer the first time, but on a refresh test they came up around the 5th sec. Still advise not showing anothing on stage until all is loaded. An alternative is to step load. Show the drawers at like 20% to indicate inactive while the spinner continues to load items is also acceptable.
- [ ] Bruce, there was a comment made about the skin color. We should discuss this. We went with blue to remove any racial bias. We can move to a pure white, but I fear because "white" is the description, we put ourselves right back into contention. Green, red, orange, yellow, purple, etc will all have the same issue as blue.
- [x] The top drawer tab and the two side ones don't have the same effect on stage. They should interact with the content below in the same way. Since the left-right sit over the organ, the top should as well, not sit in a black bar.
Organ Carousel/L Drawer
- [ ] Ontotology and Organ Carousel still not in sync. No state sync for active/inactive items.
- [ ] Counts seem to change at will. I have managed to set counts to zero, then have them update later after clicking an organ.
- [ ] Organ Carousel looks like it now enable/disables items on Stage. Saw the addition of skin item.
- [ ] Organ Carousel and Ontology leave me confused. Spleen shows 15 items, but there is nothing at the sub-levels in the ontology, only at the top item level. Lung, skin and small intestine appear in the Ontology but not in the Carousel.
- [x] Large Intestine text looks odd since it is out of alignment, the space between icon and text compressed. NOTE: Per Katy and the ontology, shouldn't the text here and in the ontology be "intestine, large"? That was the mandate for the CCF Portal.
- [x] L Drawer Filter Icon does not have a properly formatted hover state. Gray needs border-radius.
- [x] Filter checkboxes have the correct hover/click states. These should be used with the Color Coded Checkboxes as well. Light gray on hover, ripple on color change at selection.
- [x] Filter sliders. It is possible for the user to click on a number and input a custom value. This potential action is not communicated in any manner. Even hover over the numbers doesn't show a cursor change. Advise adding the bottom border used on other inputs. Also, add the pointer cursor on hover. Adding a gray background to the input on hover would be a futher indicator. The numbers themselves are ending up clipped on the right if three digit. Adjust the width of the input as necessary.
- [x] Filter Reset button needs hover state. Should function like other icons.
- [x] Filter Close should have animation. The Filter area has an open animation, it needs a close that is the reverse.
- [ ] Ontology. Noticing that clicking on sub-items (e.g. left kidney) activates a count. Why? A "0" means there is nothing to see. De-incentivizes the user from clicking. If there are counts, they should be shown.
R Drawer
- [x] R Drawer Results area uses a gradient overlay at the bottom to indicate additional items follow. Looks like something is in place but it is minimal. Needs to be much stronger. The bottom demarcation between results and frame should be soft.
- [x] The R Drawer checkboxes are not correct for selected state. Looks like it is loading the text "checkbox" instead of the icon with the checked state.
- [x] R Drawer Reset Icon doesn't seem to do anything.
- [ ] R Drawer Metadata. Changing organs in Carousel has no impact. Only changes to the Ontology. Both triggers should impact Metadata.
- [x] R Drawer header should be in format "Body", non-bold, and larger 20px font size.
- [x] R Drawer Metadata should be bold for numbers (600) and normal light for text (300). It seems that the same style rule is applied to both this section and the Results for the normal text. I'm fine with that. Use the same 600 / 300 mix as for Metadata. NOTE: OK to use 700 for the bold, I'm liking the 600 more, but use your judgement.
- [x] Results. The hover states seem to work for external links.
- [x] Carousel in Result Card. On the right I see the gradient when there are more items, this pattern should be repeated as appropriate on the left. There also appears to be a bit of bleed where it is larger than the card extending beyond the bottom.
- [x] NOTE: Use of font-weight: bolder is not a sound practice. An increment of 100 does create enough contrast for most people to make a discernment. As with metadata, for Filter Metadata, move to label 300 and value 600 or 700.
- [ ] When the user has multiple organs active, the text in the Results doesn't help to identify what card goes with what organ. We may want to include additional meta in the main header (e.g. kidney, female, age 38, etc).
- [x] Results should have a hover state. When the user mouses over inactive Result items the state change proposed elsewhere for the checkbox needs to occur. The checkbox and card are linked for functionality.
Stage
- [ ] Organ rotation. Odd. I got two different behaviors. Not sure why. In one instance, I can manuver around the individual organ, which is a big improvement. However, in another instance I was again rotating the entire two bodies.
- [ ] Organ Rotation. There needs to be some helper text to let the user know that use of SHIFT+drag, CTRL+drag, or ALT+drag contrains to moving the organ about on stage, not rotation. A toaster might be enough. On enter Stage it could animate in for say ten seconds, then animate out.
- [ ] RUI blocks seem to exist outside of the organ. This is a problem from what I understand.

**Comment by hrishikeshpaul** [comment]
> The top drawer tab and the two side ones don't have the same effect on stage. They should interact with the content below in the same way. Since the left-right sit over the organ, the top should as well, not sit in a black bar.
Organ Carousel/L Drawer

Could you please elaborate on this?

**Comment by hrishikeshpaul** [comment]
> Large Intestine text looks odd since it is out of alignment, the space between icon and text compressed. NOTE: Per Katy and the ontology, shouldn't the text here and in the ontology be "intestine, large"? That was the mandate for the CCF Portal.

What should be done about this? Even if we change it to "Intestine, Large" it will still be out of alignment

**Comment by bherr2** [comment]
@lecross ?

**Comment by lecross** [comment]
Drawer tab integration with Stage should be identical for all three tabs. The left and right tabs sit over the top of the content on Stage. The top tab sits in a black bar with the Stage content below it. The three tabs should be consistent in their integration with content on Stage. Extend Stage content the height of the top tab to sit flush against the Organ Carousel; or, give the left and right tabs black bars that frame the content. The goal is to make the three tab areas look the same.

**Comment by lecross** [comment]
The Organ Carousel tiles are a problem. We want to minimize overall height, yet cram content in. You can't decrease the line-height because that is already tight. You can steel a few pixels of space from the bottom of the numbers, but probably no more than 8px. So, I would add the 8px to the bottom of the icon, top of the text area, or as padding in one of those areas to push the text down from the icon. Then, align the text at organ name text at the top of the container. Currently, the text sits center-center when it should be top-center. This will pull the text into alignment at the top of the container and create the needed space with the icon.

**Comment by hrishikeshpaul** [comment]
> Drawer tab integration with Stage should be identical for all three tabs. The left and right tabs sit over the top of the content on Stage. The top tab sits in a black bar with the Stage content below it. The three tabs should be consistent in their integration with content on Stage. Extend Stage content the height of the top tab to sit flush against the Organ Carousel; or, give the left and right tabs black bars that frame the content. The goal is to make the three tab areas look the same.

Well the black bar for the top drawer tab is required otherwise you can't get the rounded corners for the stage. I'll see if I can make a workaround for that

**Comment by lecross** [comment]
You may need to move to graphical solutions. As example, using a small image that contains the corners, where the graphic is part white and part transparent. Or using CSS to shape a corner by drawing it. Remind me what the issues are with the Organ Carousel, top tab, and the Stage. A simple inspect via the browser doesn't necessarily provide me a complete picture.

**Comment by hrishikeshpaul** [comment]
That wasn't required. I played around with a few CSS settings and the positions.

**Comment by lecross** [comment]
So you did an absolute position? Negative margin? Feed the curious brain. :-)

**Comment by hrishikeshpaul** [comment]
Yes! I had to use absolute positioning. The behavior of the `height` property is to increase top-down. To reserve it and make to down-top you need to use absolute position. So then it was just a matter of calculating the height that the stage needs to be increased to!
