### ISSUE TITLE
Handle v1.1 Rescaled 3D Models

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#613]
Kristen had to make some adjustments to the 3D models which change some scaling and placement of the models. Use her mappings to ensure that registered data still places correctly when v1.1 organs are integrated.

See email: `Scaled models uploaded` from `Fri 6/25/2021 9:02 PM`

**Comment by andreasbueckle** [comment]
This issue has been resolved for the large intestine tissue blocks (Yiing Lin re-registered them). Not solved for any other organ.
