### ISSUE TITLE
Add, remove, or restructure Google Analytics event based on pilot preprocessing and analysis workflow in R

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#653]
While we continue to analyze the data already captured via Google Analytics, we should aim to refine the existing events we defined in our code. Data preprocessing and analysis go hand in hand with this improvement process.

**Comment by andreasbueckle** [comment]
Refinement ongoing.

**Comment by bherr2** [comment]
@andreasbueckle Can this issue be closed?

**Comment by andreasbueckle** [comment]
Yes.
