### ISSUE TITLE
Colon has five extraction sites, but one of them contains the other four

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#654]
In the RUI, the colon has five extraction sites, but one of them contains the other four, see below. Seems like the extraction site "HuBMAP colon extraction sites" is not needed. Weren't the other four also given by HuBMAP experts anyway? 

![image](https://user-images.githubusercontent.com/22821046/129773449-44b974ae-3833-4040-b4ce-9940a438cb06.png)

**Comment by bherr2** [comment]
Yeah, it needs removed. I think others are like this, just haven't had time to address it.

**Comment by andreasbueckle** [comment]
Same for the heart: https://github.com/hubmapconsortium/ccf-ui/issues/597

**Comment by bherr2** [comment]
Edward committed a quick fix, but I also need to remove from the mapping file and regenerate the data.

**Comment by andreasbueckle** [comment]
Looks like the issues persists: 

![image](https://user-images.githubusercontent.com/22821046/145110073-186b5541-47fd-4758-8358-55994d6ff85c.png)
