### ISSUE TITLE
Missing texture for human gizmo? 

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#663]
Received this issue from a new RUI user. Very odd could not replicate the problem on my machine, even after resizing the window and taking the same camera perspective. 

Her note: 
"There's a white box with a frowning face near the coordinates. See yellow box highlighting this strange icon."

![image](https://user-images.githubusercontent.com/22821046/131943994-8e5c0535-1614-4235-8611-1e69be2b0dbd.png)

**Comment by bherr2** [comment]
@andreasbueckle Please find out the OS/Browser version she used. I believe it is a webgl crash on a specific browser (I'm guessin g Safari). Does it happen every time? Has she tried another browser?

**Comment by andreasbueckle** [comment]
Sounds good @bherr2 , I just email her. Will replay her reply once I have it.

**Comment by andreasbueckle** [comment]
@bherr2 
My Qs to Andrea Radtke and her replies:

    What operating system did you use? **Windows 10** 
    What browser version did you use? Bruce believes it is a WebGL crash on a specific browser (probably Safari). **Google Chrome is up to date: Version 93.0.4577.63 (Official Build) (64-bit)**
    Does it happen every time? **No**
    Have you tried another browser? **No**

**Comment by andreasbueckle** [comment]
Follow-up email from the user:
No crash. Wasn’t able to move and register “yellow block” for skin and vasculature. Andi thinks it’s the large scale of those 2 tissues, difficult to zoom in/precisely place the block.
There  also was a  little “Frowny face icon” near the x,y,z coordinates.
Guinea pig testing is key😊

**Comment by andreasbueckle** [comment]
Still relevant? Can close otherwise.

**Comment by bherr2** [comment]
This was fixed in the v2.3.5 release.
