### ISSUE TITLE
Lung not shown in EUI

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#686]
While the lung is listed in the partonomy on the left, the 3D model is not, and it cannot be turned on either:

![image](https://user-images.githubusercontent.com/22821046/134579208-b296332f-8f08-4fcd-bf8c-529a4bfdd1c0.png)

**Comment by bherr2** [comment]
Fixed in [v2.3.5](https://github.com/hubmapconsortium/ccf-ui/releases/tag/2.3.5)
