### ISSUE TITLE
Tissue blocks in organ view web component not clickable

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ccf-ui#688]
The cursor changes when hover in over the tissue blocks but they don't seem to be clickable (I tried Safari and Chrome). Are they meant to be clickable?

https://portal.stage.hubmapconsortium.org/organ/thymus

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/1216518/134725518-e0e324e9-fc9f-4eaa-9bba-db8dd4d4aa2b.png">

**Comment by bherr2** [comment]
They are not meant to be clickable (thought it's not out of the realm of possibility)

**Comment by ngehlenborg** [comment]
The changing cursor indicates to me that something should happen when I hover over a block. Maybe the cursor can be left unchanged unless there's some event tied to hovering or clicking?
