### ISSUE TITLE
Colon Tissue Blocks Shown in Wrong Ref Body?

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#690]
We have 4 colon tissue blocks, all female, according to the details pane. But they are all shown in the male ref body:

Might have been an error on the side of the user. The RUI JSON file references the VHM colon in the target property of the placement object:
https://portal.hubmapconsortium.org/dev-search?entity_type%5b0%5d=Sample&anatomy_1-anatomy_2-anatomy_3-anatomy_4-anatomy_5%5b0%5d%5b0%5d=abdominal%20cavity&anatomy_1-anatomy_2-anatomy_3-anatomy_4-anatomy_5%5b1%5d%5b0%5d=colon&has_rui_sample=true&view=ccf

![image](https://user-images.githubusercontent.com/22821046/135154273-ea84f3c4-73c1-4a92-89f3-4db7b4c89ab1.png)

**Comment by bherr2** [comment]
Fixed in CCF 3.0
