### ISSUE TITLE
A new way to select organs

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#729]
Now that we have FIFTY reference organs, the carousel style selector is not great for selecting organs. We need to think of a new UI to do this. Perhaps as a dropdown/modal that shows the organs in a grid for selection. Needs discussion/SPECS.

**Comment by bherr2** [comment]
CC @katyb @andreasbueckle

**Comment by andreasbueckle** [comment]
Maybe a selection grid like in video game inventory systems (see below) where there might be hundreds of items. We may then even think about grouping them into tabs. Unsure how the SPECing works now, but that would be a good practical example. 

![image](https://user-images.githubusercontent.com/22821046/149387969-f26605b4-051b-40c6-80a0-ef4f097276d8.png)

**Comment by bherr2** [comment]
![image](https://user-images.githubusercontent.com/34098595/153894719-074983d9-525c-480d-82ce-1601327044b3.png)
