### ISSUE TITLE
Feature request: PRIORITY sex specificity restriction

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-ui#783]
@katyb @bherr2 @andreasbueckle

I realized today that there is not a restriction to prevent RUI users from registering a sex specific organ with the wrong sex.

Example:  I can select fallopian tube and if I forget to switch the slider to female, I could register a tissue block where metadata would have male. 

This should be prevented for all sex specific organ registrations, in my opinion, it's too easy to space out on this one.
Female only: ovary, fallopian tube, uterus (we will have more in future)
Male only: prostate (we will have more in future)

**Comment by bherr2** [comment]
If you select a sexed organ and have the opposite sex chosen, it'll automatically switch the sex for you.
