### ISSUE TITLE
Dynamic height for Filter popup

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#798]
Right now the Filter popup has a set height, but this changes based on the number of technologies/assay types/etc in the Filter. Update the logic so that the filter height can update dynamically.

**Comment by edlu77** [comment]
This has been fixed

https://github.com/hubmapconsortium/ccf-ui/pull/864/files#diff-0bc34ace3a22db65b879757478d338732c5b5e84a0278b71699830281e34913e
