### ISSUE TITLE
2 GTEx extraction sites misplaced

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#799]
See 
![image](https://user-images.githubusercontent.com/34098595/163436141-a477d458-5502-45c1-9732-5c2a75ef8a51.png)

I think these may have a wrong placement target or duplicate IDs, but haven't looked into it yet.

**Comment by bherr2** [comment]
CC @andreasbueckle

**Comment by andreasbueckle** [comment]
Thanks for the note @bherr2 
Is any action required from me?

**Comment by bherr2** [comment]
If you could do a quick check of the gtex rui_locations.jsonld that'd be much appreciated.

**Comment by bherr2** [comment]
Might be something obvious.

**Comment by andreasbueckle** [comment]
Proposed fix: https://github.com/hubmapconsortium/ccf-ui/pull/800

**Comment by bherr2** [comment]
Thanks!
