### ISSUE TITLE
Add WASDQE annotations from spatial search to tissue block in RUI

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#878]
@bherr2 
Might help users understand how keys map to direction.

**Comment by andreasbueckle** [comment]
Prototype: https://cns-iu.github.io/rui-3d-interactions/
![image](https://github.com/hubmapconsortium/ccf-ui/assets/22821046/daf1a4b9-46d9-44e0-a9d2-1b321962c385)

**Comment by libby-maier** [comment]
## UX Notes
- Use the same interface and functionality for the WASDQE keypad from the EUI's Spatial Search. Position this on the right side of the RUI scene. The keys should light up just as it does in the EUI's Spatial Search.
- Use the same arrows and keys for the tissue block as used on the probing sphere in the EUI. The exact same look and feel is desired.

## Resources
- [Exploration User Interface (EUI)](https://portal.hubmapconsortium.org/ccf-eui)
- [RUI Figma design file: WASDQE keypad](https://www.figma.com/file/KMti4IJGUUQrle2rl1n2Go/RUI?type=design&node-id=683-541&mode=design&t=PhMlvOm1lUoGC8KU-4)
- [EUI Spatial Search design file: WASDQE keypad](https://www.figma.com/file/AxRgTJl5PUE7tNqk0VsMc3/EUI?type=design&node-id=680-25741&mode=design&t=uMZAgIRhQPjvL2Zf-4)
- [Unity prototype: Tissue block annotations (arrows & keys)](https://cns-iu.github.io/rui-3d-interactions/)


## EUI Spatial Search Reference Images
### Probing sphere annotations:
![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/74dad5ff-d4ec-4689-bf08-edf3baabda5d)

### Keypad functionality
![456761AE-226B-4700-A84B-1CE0798827F2](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/00581074-204d-4077-b2a5-7bb33b9479ef)

**Comment by bherr2** [comment]
@edlu77 This was working, but your recent changes have made it disappear. You break it, you fix it!

**Comment by bherr2** [comment]
@edlu77 also, keyboard WASDQE entry no longer works. You break it, you fix it!

**Comment by bherr2** [comment]
Fixed on develop
