### ISSUE TITLE
Tissue Block Controls - Right Side Module

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#879]
@bherr2 
It would be good to be able to reset individual XYZ rotation sliders in case one messes up only one axis.

**Comment by libby-maier** [comment]
I designed a number input for this feature and it is pending approval from Bruce & Katy. 

These inputs are housed in the Tissue Block Controls Right Side Module.

Below is the current state of this component and feature request:

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/cef089ea-9649-49e1-9125-3dc3b24ba0b9)
