### ISSUE TITLE
Removing "Previously Registered Button"

### ISSUE THREAD

**Issue by dw-dot** [hubmapconsortium/ccf-ui#888]
Andi - I think we should consider retiring the Previously Registered Blocks button. I am not aware of any user that has ever successfully used it; we do not cover it in our documentation because I have trouble seeing its value (seeing those previously registered blocks looks cool, but that's it); it shows different things to different people based on their browser; and now it seems to be causing confusion.

**Comment by libby-maier** [comment]
Move the upload button to either the top left or the entry point. It needs to be more prominent!

Test Previously Registered Button functionality.

![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/945263d8-266d-417b-bd2f-59c1fb695985)

**Comment by libby-maier** [comment]
Figma design file: https://www.figma.com/file/KMti4IJGUUQrle2rl1n2Go/RUI?type=design&node-id=449%3A1136&mode=design&t=PhMlvOm1lUoGC8KU-1

**Comment by libby-maier** [comment]
Please note that this is getting replaced by the Registration Metadata module.

Reach out with questions if you have them!
