### ISSUE TITLE
Remove "TMC-" prefix in TMC selector

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#92]
To gain back some more space, do not prefix TMCs with a TMC- prefix.

**Comment by KalaRaja** [comment]
wouldnt the label be coming from the data ?
if yes, would it make sense to hard code the removal of 'TMC-' prefix?

**Comment by axdanbol** [comment]
Yes, because the items are called tmc and is very likely to contain 'TMC-' as a prefix.
