### ISSUE TITLE
Allow user to move block along local axis in addition to global axis?

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#933]
Currently, the user can only move along the global axes. It is common in 3D software to let the user choose between global and local axes for position adjustments. 

![image](https://user-images.githubusercontent.com/22821046/180029257-2d146a1a-1088-4cc6-988a-589cccf757ef.png)

**Comment by andreasbueckle** [comment]
Note that we have this build to test this with users now: https://cns-iu.github.io/rui-3d-interactions/

**Comment by libby-maier** [comment]
This has been tested and users prefer global navigation settings. @andreasbueckle should we close this issue?
