### ISSUE TITLE
dataset counts in the HRA organ-level spatial view web component are different from the portal dataset counts

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ccf-ui#948]
Dataset counts in the portal-embedded HRA organ-level spatial view web component are different from the portal dataset counts, e.g., https://portal.hubmapconsortium.org/organ/liver#organ%20info. The data portal has 12 (if we count the raw data sets separately, otherwise there are 6) dataset but apparently the HRA has only 3 for male and 3 for female. The [dataset search shows](https://portal.hubmapconsortium.org/search?entity_type%5B0%5D=Dataset&origin_sample.mapped_organ%5B0%5D=Liver) that there are 8 for male (4 if only counting raw) and 4 for female (2 if only counting raw).

<img width="1324" alt="image (37)" src="https://user-images.githubusercontent.com/1216518/192527716-04e15b4f-1e09-4e6c-8a3d-726b19bcd65f.png">

<img width="1324" alt="image (38)" src="https://user-images.githubusercontent.com/1216518/192527708-72e549e1-ada8-494c-b772-547d4293f71d.png">

The conceptual issue here is that if the atlas is an atlas and not a data portal then it should probably not be displaying dataset counts. If the atlas is meant to display HuBMAP datasets, then we need to ensure that the counts displayed in the portal and in the atlas are matching.

**Comment by bherr2** [comment]
Remember our numbers are based off of the samples which are RUI located. All other datasets/samples/etc are ignored (EUI is NOT a data portal, it's an Atlas interface).

So, this picks up 2 samples (in public version):

- [HBM386.CMDS.872](https://portal.hubmapconsortium.org/browse/sample/ab957eb5a977b2eeb8817bc180bde4df) (Female)
- [HBM355.SRXZ.437](https://portal.hubmapconsortium.org/browse/sample/46168dd8aab589ce7edfa4beeaed773e) (Male)

Each of those samples has two datasets in the EUI. Then we also include Linked Open Data from other consortia. And for Liver we have one Donor and one Dataset per rui location from GTEx. Thus we arrive at the 2 tissue blocks + 3 tissue datasets per sex.

**Comment by bherr2** [comment]
> If the atlas is meant to display HuBMAP datasets, then we need to ensure that the counts displayed in the portal and in the atlas are matching.

The EUI / HRA is meant to show the Datasets (ie experimental data) which has been mapped to the HRA. Thus if the Dataset's sample hasn't been RUI Located (ie mapped to the HRA), then it will not show in the EUI / HRA User Interfaces.

I see the reason you bring it up (could cause confusion). I'm open to finding a solution here, perhaps a labeling/framing change could help, but I'm not quite sure what that'd be. 

I CC @katyb and @libby-maier for their input. Maybe during our next joint UX (IU + Harvard) design meeting, we could start to address the conceptual issue.

**Comment by ngehlenborg** [comment]
I see two possible solutions:

1. a version of the web component that allows us to configure it so that it only displays HuBMAP data
2. we remove the web component from the portal and just provide a link out to avoid confusion

**Comment by bherr2** [comment]
We can definitely do 1 (the web component can be easily configured to do that), but it doesn't address HRA-mapped vs non-HRA-mapped hubmap data.

**Comment by bherr2** [comment]
I setup a PR to do 1 here: <https://github.com/hubmapconsortium/portal-ui/pull/2930>
